{"uuid":"91042812-3779-416a-8161-5b24dd37ea09","historyId":"db1bc3ff1695924f0ddf6363259b770f","fullName":"com.usga.qa.tests.AndroidPlayerSearch.verify_favplayer_in_leaderboard_Android","labels":[{"name":"package","value":"com.usga.qa.tests.AndroidPlayerSearch"},{"name":"testClass","value":"com.usga.qa.tests.AndroidPlayerSearch"},{"name":"testMethod","value":"verify_favplayer_in_leaderboard_Android"},{"name":"parentSuite","value":"Suite"},{"name":"suite","value":"Test"},{"name":"subSuite","value":"com.usga.qa.tests.AndroidPlayerSearch"},{"name":"host","value":"USBLRSOMEGHANA1"},{"name":"thread","value":"2140@USBLRSOMEGHANA1.TestNG-test=Test-1(39)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"verify_favplayer_in_leaderboard_Android","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. \nHost info: host: 'USBLRSOMEGHANA1', ip: '192.168.1.2'","trace":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. \nHost info: host: 'USBLRSOMEGHANA1', ip: '192.168.1.2'\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)\n\tat io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:229)\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:80)\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:92)\n\tat io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:117)\n\tat com.usga.qa.base.BaseClass.androidinitialization(BaseClass.java:80)\n\tat com.usga.qa.tests.AndroidPlayerSearch.setup(AndroidPlayerSearch.java:32)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\nCaused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException\nBuild info: version: '4.6.0', revision: '79f1c02ae20'\nSystem info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.4', java.version: '19.0.1'\nDriver info: driver.version: AndroidDriver\n\tat io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:130)\n\tat io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)\n\tat io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:155)\n\tat io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:189)\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)\n\t... 18 more\nCaused by: java.lang.reflect.InvocationTargetException\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\n\tat io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:126)\n\t... 22 more\nCaused by: java.io.UncheckedIOException: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat io.appium.java_client.remote.AppiumCommandExecutor.lambda$createSession$0(AppiumCommandExecutor.java:158)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat io.appium.java_client.remote.AppiumCommandExecutor.lambda$createSession$0(AppiumCommandExecutor.java:158)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:122)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\n\t... 24 more\nCaused by: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed\n\tat org.asynchttpclient.exception.RemotelyClosedException.INSTANCE(Unknown Source)\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg2","value":"4"},{"name":"arg1","value":"Jason Day"},{"name":"arg0","value":"U.S. Open"}],"start":1686732606304,"stop":1686732606305}